// Run against a local resources server: U1_TEST_URL=http://127.0.0.1:18791/web/model-library/index.html node tests/web/model-library.cjs
const { chromium } = require('playwright');
const assert = require('node:assert/strict');
(async () => {
  const browser = await chromium.launch({ channel: 'chrome', headless: true });
  const page = await browser.newPage({ viewport: { width: 1280, height: 1000 } });
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.addInitScript(() => { window.sent = []; window.wx = { postMessage: m => window.sent.push(JSON.parse(m)) }; });
  const url = process.env.U1_TEST_URL || 'http://127.0.0.1:18791/web/model-library/index.html';
  await page.goto(url + '?library=1');
  await page.getByRole('heading', { name: 'Sua próxima criação começa aqui.' }).waitFor();
  assert.equal(await page.locator('dialog').evaluate(e => e.open), true);
  await page.getByRole('searchbox').fill('vaso & café / U1');
  await page.getByRole('button', { name: 'Buscar no MakerWorld' }).click();
  let sent = await page.evaluate(() => window.sent);
  assert.equal(sent[0].command, 'common_openurl');
  assert.equal(new URL(sent[0].url).searchParams.get('keyword'), 'vaso & café / U1');
  await page.getByRole('button', { name: 'Buscar no Printables', exact: false }).first().click();
  sent = await page.evaluate(() => window.sent);
  assert.equal(new URL(sent[1].url).hostname, 'www.printables.com');
  await page.getByRole('button', { name: 'Buscar no Thingiverse' }).click();
  sent = await page.evaluate(() => window.sent);
  assert.equal(new URL(sent[2].url).searchParams.get('q'), 'vaso & café / U1');
  await page.getByRole('button', { name: 'Salvar um link' }).click();
  await page.getByLabel('Nome do projeto').fill('<img src=x onerror=alert(1)> Organizador');
  await page.getByLabel('Link do modelo').fill('https://www.printables.com/model/123');
  await page.getByRole('button', { name: 'Salvar ideia', exact: true }).click();
  await page.reload();
  await page.getByRole('button', { name: '<img src=x onerror=alert(1)> Organizador www.printables.com' }).waitFor();
  assert.equal(await page.locator('img').count(), 0);
  await page.getByRole('button', { name: 'Salvar um link' }).click();
  await page.getByLabel('Nome do projeto').fill('Duplicado');
  await page.getByLabel('Link do modelo').fill('https://www.printables.com/model/123');
  await page.getByRole('button', { name: 'Salvar ideia', exact: true }).click();
  assert.match(await page.getByRole('status').innerText(), /já está/);
  await page.getByLabel('Link do modelo').fill('http://example.com/');
  await page.getByRole('button', { name: 'Salvar ideia', exact: true }).click();
  assert.match(await page.getByRole('status').innerText(), /HTTPS válido/);
  await page.getByRole('button', { name: 'Cancelar', exact: true }).click();
  await page.getByRole('button', { name: 'Remover <img' }).click();
  await page.reload();
  assert.equal(await page.locator('.bookmark').count(), 0);
  await page.getByRole('button', { name: 'Organização', exact: true }).click();
  assert.equal(await page.getByRole('searchbox').inputValue(), 'desk organizer');
  await page.keyboard.press('Escape');
  assert.equal(await page.locator('dialog').evaluate(e => e.open), false);
  await page.getByRole('button', { name: 'Explorar modelos' }).click();
  if (process.env.U1_SCREENSHOT) await page.screenshot({ path: process.env.U1_SCREENSHOT });
  await page.setViewportSize({ width: 390, height: 844 });
  assert.equal(await page.locator('dialog').evaluate(e => e.scrollWidth <= e.clientWidth + 1), true);
  // A corrupt store must not be silently overwritten.
  await page.evaluate(() => localStorage.setItem('u1-lab:model-links:v1', '{invalid'));
  await page.reload();
  assert.equal(await page.getByRole('button', { name: 'Salvar um link' }).isDisabled(), true);
  assert.match(await page.getByRole('status').innerText(), /não será substituído/);
  // Real browser fallback opens a separate page, keeping the library in place.
  await page.evaluate(() => { delete window.wx; localStorage.clear(); });
  await page.route('https://www.printables.com/**', route => route.fulfill({ body: 'External site test' }));
  const popupPromise = page.waitForEvent('popup');
  await page.getByRole('button', { name: 'Explorar Printables' }).click();
  const popup = await popupPromise;
  await popup.waitForLoadState();
  assert.equal(new URL(popup.url()).hostname, 'www.printables.com');
  assert.deepEqual(errors, []);
  await browser.close();
  console.log('PASS: search encoding, native bridge, saved links, persistence, duplicate/URL validation, safe text, deletion, keyboard, responsive layout, corrupt storage, browser fallback.');
})().catch(error => { console.error(error); process.exit(1); });
