// Isolated contract tests. Fixtures are explicitly synthetic; native/live checks are separate.
const { chromium } = require('playwright');
const assert = require('node:assert/strict');
(async () => {
  const browser = await chromium.launch({channel:'chrome',headless:true});
  const page = await browser.newPage({viewport:{width:1280,height:1000}});
  const errors=[],popups=[];page.on('pageerror',e=>errors.push(e.message));page.on('popup',p=>popups.push(p));
  // The image CDN rejects requests carrying the local app's Referer.
  const imageHeaders=[];
  await page.route('https://cdn.thingiverse.com/test-*.png',async route=>{
    const headers=route.request().headers();imageHeaders.push(headers);
    if(headers.referer)return route.fulfill({status:403,body:'Referrer rejected'});
    await route.fulfill({contentType:'image/png',body:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=','base64')});
  });
  let saved=[], releasePage;
  const delayedPage=new Promise(resolve=>releasePage=resolve);
  await page.exposeFunction('fixtureBridge',async m=>{
    if(m.command==='u1_search' && m.provider==='snapmaker' && m.page===2)await delayedPage;
    if(m.command==='u1_mw_status'||m.command==='u1_mw_disconnect')return {connected:false};
    if(m.command==='u1_mw_connect')return {verification:true};
    if(m.command==='u1_mw_verify')return {connected:true};
    if(m.command==='u1_mw_resolve')return {title:'Projeto multicolorido',creator:'Criador',license:'CC BY',summary:'<p>Descrição</p><script>window.hacked=true</script>',profiles:[{id:'12345',title:'Perfil azul e branco',plates:[{index:1,filaments:[{color:'#FFFFFF',type:'PLA'},{color:'#305ABD',type:'PLA'}]}]}]};
    if(m.command==='u1_mw_search')return {total:150,hits:Array.from({length:m.page===1?100:50},(_,i)=>({id:978489+(m.page-1)*100+i,title:'Blue shell '+((m.page-1)*100+i),designCreator:{name:'Criador MakerWorld'},cover:'https://cdn.thingiverse.com/test-mw.png'}))};
    if(m.command==='u1_mw_import')return {imported:true};
    if(m.command==='u1_status')return {thingiverse:false};
    if(m.command==='u1_configure_thingiverse')return {thingiverse:true};
    if(m.command==='u1_load_favorites')return saved;
    if(m.command==='u1_save_favorites'){saved=m.items;return true;}
    if(m.command==='u1_filaments')return [{id:1,color:'#FFFFFF'},{id:2,color:'#FF0000'}];
    if(m.command==='u1_files')return [{key:'900-1',name:'Corpo.stl',extension:'.stl',thumbnail:'https://cdn.thingiverse.com/test-part.png'},{key:'900-2',name:'Lingua.stl',extension:'.stl'}];
    if(m.command==='u1_download_file')return {downloaded:true};
    if(m.command==='u1_open_downloads')return {imported:true};
    if(m.command==='u1_detail' && m.provider==='thingiverse')return {name:'Modelo com peças',description:'Peças do criador'};
    if(m.command==='u1_detail')return {import_available:true,data:{name:'Peça de teste',pics:['https://cdn.thingiverse.com/test-detail.png'],description:'<p>Descrição <strong>segura</strong></p><script>window.hacked=true</script><a href="https://example.com">link</a>',copyright:{content:'Atribuição obrigatória'}}};
    if(m.command==='u1_import')return {imported:true};
    if(m.provider==='thingiverse' && m.query==='')return {total:150,hits:Array.from({length:m.page===1?100:50},(_,i)=>({id:2000+(m.page-1)*100+i,name:'Modelo recente '+i,creator:{name:'Maker'}}))};
    if(m.provider==='thingiverse' && m.query==='wife')return {total:3,hits:[{id:901,name:'Wireless box',creator:{name:'Maker'}},{id:902,name:'Happy wife plaque',creator:{name:'Maker'}},{id:903,name:'Wife keychain',creator:{name:'Maker'}}]};
    if(m.provider==='thingiverse')return {total:22,hits:[{id:900,name:'Resultado Thingiverse',creator:{name:'Criador'},thumbnail:'https://cdn.thingiverse.com/test-image.png'}]};
    if(m.command==='u1_search')return {code:200,page:{total:30},data:{models:Array.from({length:15},(_,i)=>({id:(m.page-1)*15+i+1,name:i===0&&m.page===1?'<img src=x onerror=alert(1)>':`Modelo ${m.page}-${i}`,creator:i%2?'Ana':'Beto',pic:'',publishedDate:i+1000,isOnlyGcode:i===3}))}};
    return {};
  });
  await page.addInitScript(()=>{window.sent=[];window.wx={postMessage:async raw=>{
    const m=JSON.parse(raw);window.sent.push(m);
    if(m.command==='get_recent_projects'){window.postMessage({command:m.command,response:[{project_name:'Cubo.3mf',path:'/test/cubo.3mf'}]});return;}
    if(!m.id)return;
    try{const data=await window.fixtureBridge(m);window.u1LibraryResponse({id:m.id,ok:true,data});}catch(e){window.u1LibraryResponse({id:m.id,ok:false,error:e.message});}
  }};});
  const url=process.env.U1_TEST_URL||'http://127.0.0.1:18791/web/model-library/index.html';
  await page.goto(url);await page.getByRole('heading',{name:'15 modelos',exact:true}).waitFor();
  await page.getByRole('searchbox').fill('Módelo');
  await page.getByRole('button',{name:'Buscar modelos',exact:true}).click();
  releasePage();
  await page.getByRole('heading',{name:'29 modelos',exact:true}).waitFor();
  await page.waitForFunction(()=>!document.querySelector('#refresh').disabled);
  await page.getByRole('searchbox').fill('');
  await page.getByRole('button',{name:'Buscar modelos',exact:true}).click();
  await page.getByRole('heading',{name:'30 modelos',exact:true}).waitFor();
  assert.equal(await page.locator('dialog,.launcher').count(),0);
  assert.equal(await page.locator('#results .card').count(),24);
  assert.equal(await page.locator('#results .card strong img').count(),0);
  await page.getByRole('button',{name:'Próxima →'}).click();assert.equal(await page.locator('#results .card').count(),6);
  await page.getByLabel('Criador',{exact:true}).selectOption('Ana');assert.equal(await page.locator('#results .card').count(),14);
  await page.getByLabel('Criador',{exact:true}).selectOption('');
  await page.getByRole('searchbox').fill('Modelo 1-1');await page.getByRole('button',{name:'Buscar modelos',exact:true}).click();
  assert.equal(await page.locator('#results .card').count(),6);
  await page.locator('#results .save').first().click();await page.reload();await page.getByRole('heading',{name:'30 modelos',exact:true}).waitFor();
  await page.getByRole('button',{name:'♡ Modelos salvos',exact:true}).click();assert.equal(await page.locator('#favorites .card').count(),1);
  await page.locator('#favorites .open-model').first().click();await page.getByRole('heading',{name:'Peça de teste',exact:true}).waitFor();
  await page.waitForFunction(()=>document.querySelector('#detail img')?.naturalWidth>0);
  assert.equal(await page.locator('#detail a,#detail script').count(),0);assert.equal(await page.evaluate(()=>window.hacked),undefined);
  await page.getByRole('button',{name:'Importar no projeto',exact:true}).click();await page.getByRole('status').filter({hasText:'Modelo baixado'}).waitFor();
  await page.getByRole('button',{name:'◷ Arquivos recentes',exact:true}).click();await page.getByRole('button',{name:'Cubo.3mf',exact:true}).click();
  await page.getByRole('button',{name:'▦ Biblioteca de modelos',exact:true}).click();
  await page.getByLabel('Plataforma',{exact:true}).selectOption('thingiverse');await page.getByRole('status').filter({hasText:'Conecte seu aplicativo'}).waitFor();
  assert.equal(await page.getByLabel('Ordenar por',{exact:true}).inputValue(),'newest');
  assert.equal(await page.locator('#results-title').innerText(),'Busca indisponível');
  assert.equal(await page.locator('#results').innerText(),'');
  assert(await page.locator('#connection-help').isVisible());
  assert.equal((await page.evaluate(()=>window.sent)).filter(m=>m.command==='u1_search'&&m.provider==='thingiverse').length,0);
  await page.getByRole('button',{name:'Pesquisar no catálogo Snapmaker',exact:true}).click();
  assert.equal(await page.locator('#status').textContent(),'');
  assert.equal(await page.locator('#results-title').innerText(),'30 modelos');
  await page.getByLabel('Plataforma',{exact:true}).selectOption('thingiverse');
  await page.getByRole('button',{name:'⌘ Integrações',exact:true}).click();await page.getByRole('button',{name:'Conectar Thingiverse',exact:true}).click();
  await page.getByRole('button',{name:'▦ Biblioteca de modelos',exact:true}).click();
  await page.getByRole('heading',{name:'150 modelos',exact:true}).waitFor();
  assert.equal(await page.locator('#results .card').count(),100);
  assert.equal(await page.getByLabel('Resultados por página',{exact:true}).inputValue(),'100');
  await page.getByRole('button',{name:'Próxima →'}).click();
  await page.waitForFunction(()=>document.querySelectorAll('#results .card').length===50);
  assert.equal(await page.locator('#page-label').innerText(),'Página 2 de 2');
  await page.getByRole('searchbox').fill('café & vaso');
  await page.locator('#advanced summary').click();await page.getByLabel('Código da licença',{exact:true}).fill('ccsa');await page.getByLabel('Publicado após',{exact:true}).fill('2026-01-01');
  await page.getByRole('button',{name:'Buscar modelos',exact:true}).click();await page.getByRole('heading',{name:'22 modelos',exact:true}).waitFor();
  await page.waitForFunction(()=>document.querySelector('#results img')?.naturalWidth>0);
  assert(imageHeaders.length>=2);assert(imageHeaders.every(h=>!h.referer));
  const sent=await page.evaluate(()=>window.sent);const search=sent.filter(m=>m.command==='u1_search'&&m.provider==='thingiverse').at(-1);
  assert.equal(search.query,'café & vaso');assert.equal(search.filters.per_page,'100');assert.equal(search.filters.sort,'relevant');assert.equal(search.page,1);assert.equal(search.filters.license,'ccsa');assert.equal(search.filters.posted_after,'2026-01-01');
  assert.equal(Object.keys(search.filters).length,18);
  await page.locator('#results .open-model').first().click();
  await page.getByRole('button',{name:'Baixar projeto completo',exact:true}).waitFor();
  assert.equal(await page.locator('#detail input:checked').count(),2);
  await page.waitForFunction(()=>document.querySelector('.part-card img')?.naturalWidth>0);
  assert(imageHeaders.every(h=>!h.referer));
  assert.equal(await page.getByLabel('Filamento de Corpo.stl',{exact:true}).inputValue(),'');
  await page.getByRole('button',{name:'Baixar projeto completo',exact:true}).click();
  await page.getByRole('status').filter({hasText:'Escolha o filamento de cada peça'}).waitFor();
  assert.equal(await page.evaluate(()=>window.sent.filter(m=>m.command==='u1_download_file').length),0);
  await page.getByLabel('Filamento de Corpo.stl',{exact:true}).selectOption('1');
  await page.getByLabel('Filamento de Lingua.stl',{exact:true}).selectOption('2');
  await page.getByRole('button',{name:'Baixar projeto completo',exact:true}).click();
  await page.getByRole('status').filter({hasText:'Projeto 3MF salvo'}).waitFor();
  const imported=await page.evaluate(()=>window.sent.filter(m=>['u1_download_file','u1_open_downloads'].includes(m.command)));
  assert.deepEqual(imported.map(m=>m.command),['u1_download_file','u1_download_file','u1_open_downloads']);
  assert.deepEqual(imported.at(-1).files,['900-1','900-2']);
  assert.deepEqual(imported.at(-1).filaments,[1,2]);
  await page.getByRole('button',{name:'← Voltar aos modelos',exact:true}).click();
  await page.getByRole('searchbox').fill('wife');await page.getByRole('button',{name:'Buscar modelos',exact:true}).click();
  await page.getByRole('heading',{name:'3 modelos',exact:true}).waitFor();
  assert.deepEqual(await page.locator('#results strong').allTextContents(),['Happy wife plaque','Wife keychain','Wireless box']);
  await page.getByLabel('Ordenar por',{exact:true}).selectOption('newest');
  await page.waitForFunction(()=>document.querySelector('#results strong')?.textContent==='Wireless box');
  await page.getByLabel('Plataforma',{exact:true}).selectOption('printables');await page.getByRole('status').filter({hasText:'Nenhuma busca foi enviada'}).waitFor();
  assert.equal(await page.locator('#results .card').count(),0);
  await page.getByRole('searchbox').fill('');
  await page.getByLabel('Plataforma',{exact:true}).selectOption('makerworld');
  await page.getByRole('heading',{name:'150 modelos',exact:true}).waitFor();
  assert(await page.locator('#catalog').isVisible());
  assert.equal(await page.locator('#results .card').count(),100);
  assert.equal(await page.getByLabel('Ordenar por',{exact:true}).inputValue(),'newUploads');
  await page.getByRole('button',{name:'Próxima →'}).click();
  await page.waitForFunction(()=>document.querySelectorAll('#results .card').length===50);
  assert.equal(await page.locator('#page-label').innerText(),'Página 2 de 2');
  await page.getByRole('searchbox').fill('blue shell');
  await page.getByRole('button',{name:'Buscar modelos',exact:true}).click();
  await page.getByLabel('Cores',{exact:true}).selectOption('true');
  await page.getByLabel('Diâmetro do bico',{exact:true}).selectOption('0.4');
  await page.getByLabel('Licença',{exact:true}).selectOption('BY-NC');
  await page.waitForFunction(()=>!document.querySelector('#refresh').disabled);
  const mwSearch=await page.evaluate(()=>window.sent.filter(m=>m.command==='u1_mw_search').at(-1));
  assert.equal(mwSearch.query,'blue shell');assert.equal(mwSearch.page,1);
  assert.deepEqual(mwSearch.filters,{sort:'score',per_page:'100',multiColor:'true',nozzleDiameters:'0.4',licenses:'BY-NC'});
  await page.getByRole('button',{name:'⌘ Integrações',exact:true}).click();
  await page.getByRole('button',{name:'Conectar conta MakerWorld',exact:true}).click();
  await page.getByRole('button',{name:'Informar código de verificação',exact:true}).click();
  await page.locator('#mw-state').filter({hasText:'Conectado'}).waitFor();
  await page.getByRole('button',{name:'▦ Biblioteca de modelos',exact:true}).click();
  await page.waitForFunction(()=>!document.querySelector('#refresh').disabled);
  await page.locator('#results .save').first().click();
  await page.waitForFunction(()=>document.querySelector('#results .save').getAttribute('aria-pressed')==='true');
  await page.locator('#results .open-model').first().click();
  await page.getByRole('heading',{name:'Perfil azul e branco',exact:true}).waitFor();
  assert((await page.locator('#detail-body').innerText()).includes('Branco'));
  assert((await page.locator('#detail-body').innerText()).includes('Azul'));
  assert.equal(await page.evaluate(()=>window.hacked),undefined);
  await page.getByRole('button',{name:'Baixar projeto com cores',exact:true}).click();
  await page.locator('#status').filter({hasText:'Projeto baixado'}).waitFor();
  const mw=await page.evaluate(()=>window.sent.filter(m=>m.command==='u1_mw_import'));
  assert.equal(mw.at(-1).profile,'12345');
  assert.equal(sent.some(m=>m.command==='common_openurl'),false);assert.equal(popups.length,0);
  await page.setViewportSize({width:390,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
  assert.deepEqual(errors,[]);await browser.close();
  console.log('PASS: full-page library, pagination, local filters, persistent favorites, safe details, native import/recent routing, Thingiverse filters, unavailable providers, no external windows, mobile layout.');
})().catch(e=>{console.error(e);process.exit(1);});
